### ISSUE TITLE
Update "1Password5 workaround" Readme chapter

### ISSUE THREAD

**Issue by n0nick** [ravenac95/sudolikeaboss#13]
Since [AgileBits fixed the browser signature verification bug in v5 .1.BETA-1](https://discussions.agilebits.com/discussion/comment/159692/#Comment_159692), I was able to work around the issue by:

1. Turning on "Beta updates" in 1Password
2. Updating 1Password (updated to 5.4.BETA-13)
3. Turning off "Verify browser code signature"
4. Using `sudolikaboss` like a boss, without installing a proxy solution.

Thought you'd want to know.

**Comment by ravenac95** [comment]
Yes! I've been meaning to update the README, but I've been insanely busy at work. I will do this very soon.

**Comment by ravenac95** [comment]
Updated finally :smile:! I apologize for the delay.
