### ISSUE TITLE
Problem with 1Password 6.3?

### ISSUE THREAD

**Issue by makromannen** [ravenac95/sudolikeaboss#23]
sudolikeaboss no longer works for me.

I've recently upgraded iTerm2 to 3.0 and 1Password to 6.3.1.

This is from the 1Password helper log:

`08/06/16 10:56:46,929 2BUA8C4S2C.com.agilebits.onepassword4-helper[2524]: 631006 [EXT:(Secondary Thread 0x7ff77ee25160):<OP4ExtensionHTTPConnection: 0x7ff77ee8c940>] M webSocketForURI: | [ES4] Extension connected Chrome-Extension 'chrome-extension://aomjjhallfgjeglblehebfpbcfeobpgk / (null)'`

`08/06/16 10:56:47,008 2BUA8C4S2C.com.agilebits.onepassword4-helper[2524]: 631006 [EXT:(Secondary Thread 0x7ff77ee25160):<OP4ExtensionClient: 0x7ff77eea3190>] E findExtensionProcessForPort: | Failed to find extension process for 'chrome-extension://aomjjhallfgjeglblehebfpbcfeobpgk:63185', my PID: 2524, invalid output: '2524
27055
', apps found: (
)`

`08/06/16 10:56:47,008 2BUA8C4S2C.com.agilebits.onepassword4-helper[2524]: 631006 [EXT:(Secondary Thread 0x7ff77ee25160):<OP4ExtensionClient: 0x7ff77eea3190>] E findExtensionProcessForPort: | Stopping connection since no PID was found to validate the other side of the connection.`

**Comment by thejandroman** [comment]
See #19.

**Comment by makromannen** [comment]
@thejandroman Thanks. Didn't think to look at closed issues.
