### ISSUE TITLE
Passwords are not sent to all panes when broadcasting input

### ISSUE THREAD

**Issue by curiositycasualty** [ravenac95/sudolikeaboss#30]
With "Broadcast Input" (a feature I've learned to love in this cold and desolate, post-csshx world) is enabled, a password collected by sudolikaboss is only sent to the first pane.

Repo:
1. open a new iTerm2 window
2. open a second pane (command+shift+d)
3. activate broadcasting input (command+option+i)
4. activate sudolikaboss, select password, and hit enter

The password in (cleartext) is only pasted into the first pane.

**Comment by ravenac95** [comment]
@curiositycasualty I too use the broadcast input feature. I've been thinking about how to get this to work but unfortunately I haven't found a way. It's definitely something I'd love to do tho.

**Comment by curiositycasualty** [comment]
RIP
