### ISSUE TITLE
Requires to Update the 1Password Extension

### ISSUE THREAD

**Issue by montanajava** [ravenac95/sudolikeaboss#32]
Pressing the shortcut displays a dialog requiring the user to update the browser extension.

Updating the extension in Firefox, Safari and Chrome did not solve the problem.

Using 1Password
![1pasword](https://cloud.githubusercontent.com/assets/6239960/20663247/1463f660-b557-11e6-8e57-8ed48ed1e7d4.png)
 6.5.2

**Comment by mouson** [comment]
The issue #29 is same problem. and it will be solve.

**Comment by Ralnoc** [comment]
@montanajava Could you close this issue? As @mouson said, #29 is tracking this issue and has a resolution that is being beta tested before final release. The new binary is actually in that thread if you wish to test if yourself.

**Comment by montanajava** [comment]
Closed because it is a duplicate.
