### ISSUE TITLE
Long delay before showing 1Password

### ISSUE THREAD

**Issue by 2bithacker** [ravenac95/sudolikeaboss#37]
Starting having an issue today where sudolikeaboss started taking a long time (20-30 seconds) before showing the 1Password window. Running it from the command line issues no errors, but sometimes fails to display the 1Password window at all and exits with error code 1.

Not really sure where to start debugging on this.

Mac OS X 10.12.3
sudolikeaboss 0.3.0-beta1
1Password 6.6.2

**Comment by csawyerYumaed** [comment]
I have the same version(s) as you do, and iTerm2 Build 3.0.15, without this problem. 

I'd guess for some reason iTerm2 is having issues making the coprocess start, have you checked for iTerm2 debugging is on and logs around coprocess starting?

The lazy way to fix this might be to restart iTerm2 and/or your mac first.

**Comment by 2bithacker** [comment]
Restarting iTerm2 had no effect, and rebooting the Mac did help, but the problem recurred. Seems to be tied to excessive disk or USB activity, but not CPU activity.

Going to close this, as I think it's a local weird issue rather than a specific sudolikeaboss issue.
