### ISSUE TITLE
Current ReadMe out of date (12/24/14)

### ISSUE THREAD

**Issue by JamesValero** [ravenac95/sudolikeaboss#9]
https://github.com/ravenac95/sudolikeaboss/blob/master/README.rst

The readme says to install 0.1 (if by source) but the workaround didn't work until I uninstalled and re-installed via homebrew and noticed 0.2 was installed instead.

**Comment by ravenac95** [comment]
Sorry for the delay. I was actually out of commission for a while. I resolved the issue
